apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: 1password
    server: https://kubernetes.default.svc
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts/
    targetRevision: 1.17.0
    helm:
      values: |
        connect:
          credentialsName: 1password-credentials
          credentialsKey: credentials
