apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - https-argocd.moholt.dev
      secretName: argocd-cert
  rules:
    - host: argocd.moholt.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  dnsNames:
    - argocd.moholt.dev
  secretName: argocd-cert
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
