apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
spec:
  rules:
    - host: raspberrypi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  name: http
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - name: http
    port: 80
    targetPort: web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: homeassistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        ports:
          - containerPort: 8123
            name: web
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: backups
          mountPath: /backup
        - name: dbus
          mountPath: /run/dbus
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-config
      - name: media
        persistentVolumeClaim:
          claimName: home-assistant-media
      - name: backups
        persistentVolumeClaim:
          claimName: home-assistant-backups
      - name: dbus
        hostPath:
          path: /run/dbus
          type: Directory
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

